#!/usr/bin/env bash
#
# walsync.sh — generate a colour palette from an image and emit it in the
# formats the rest of the rice consumes.
#
# Usage:
#   ./walsync.sh wire                   # add wal.css link to every theme's bar.html
#   ./walsync.sh unwire                 # remove it again
#   ./walsync.sh source <image>         # remember which image drives the palette
#   ./walsync.sh gen [image]            # build palette + wal.css (uses saved source if omitted)
#   ./walsync.sh gen <image> -b wal     # pick a different pywal backend
#   ./walsync.sh sync [image]           # gen + glaze + restart Zebar (use after a wallpaper change)
#   ./walsync.sh glaze                  # push palette into GlazeWM border colours
#   ./walsync.sh show                   # print the current palette
#   ./walsync.sh we-current [key]       # show the wallpaper currently on that monitor
#   ./walsync.sh watch [seconds]        # resync automatically when WE's wallpaper changes
#   ./walsync.sh we-scan                # list Wallpaper Engine wallpapers + previews
#
# Backends worth trying: haishoku (default here), colorthief, wal, colorz.
#
# Requires: python + pywal16  (pip install pywal16 haishoku colorthief)

set -euo pipefail

BACKEND="haishoku"
CACHE="$HOME/.cache/wal/colors.json"
CSS_OUT="$HOME/.glzr/zebar/dotfile-bar/wal.css"
SOURCE_FILE="$HOME/.config/walsync/source"

have() { command -v "$1" >/dev/null 2>&1; }

wal_cmd() {
  # pywal16 installs as `wal`; on Windows it may only exist as a python module.
  if have wal; then wal "$@"
  else python -m pywal "$@"
  fi
}

set_source() {
  mkdir -p "$(dirname "$SOURCE_FILE")"
  printf '%s\n' "$1" > "$SOURCE_FILE"
  echo "Palette source set to: $1"
}

gen() {
  local img="${1:-}"
  if [ -z "$img" ]; then
    if img="$(we_current 2>/dev/null)" && [ -n "$img" ]; then
      echo "Auto-detected wallpaper for $WE_MONITOR_KEY: $img"
    elif [ -f "$SOURCE_FILE" ]; then
      img="$(cat "$SOURCE_FILE")"
      echo "Auto-detect failed; using saved source: $img"
    else
      echo "No image given, auto-detect failed, and no saved source."
      echo "Run: $0 we-current   to debug, or: $0 gen <image>"
      exit 1
    fi
  fi
  [ -f "$img" ] || { echo "No such image: $img"; exit 1; }
  set_source "$img" >/dev/null

  local winimg b tried ok
  winimg="$(cygpath -w "$img" 2>/dev/null || printf '%s' "$img")"
  ok=0
  tried=""

  # Some images (near-monochrome ones especially) make a backend return fewer
  # than 16 colours, which pywal then crashes on. Fall through to another.
  for b in "$BACKEND" colorthief wal colorz; do
    case " $tried " in *" $b "*) continue ;; esac
    tried="$tried $b"
    if wal_cmd -i "$winimg" --backend "$b" -n -s -t -e 2>/dev/null; then
      BACKEND="$b"; ok=1; break
    fi
    echo "  backend '$b' failed, trying next..."
  done

  if [ "$ok" -eq 0 ]; then
    echo "All backends failed on: $img" >&2
    echo "Keeping the existing palette." >&2
    return 1
  fi

  [ -f "$CACHE" ] || { echo "pywal did not write $CACHE"; exit 1; }
  echo "Palette written to $CACHE (backend: $BACKEND)"
  emit_css
  show
}

emit_css() {
  mkdir -p "$(dirname "$CSS_OUT")"
  {
    echo "/* generated by walsync.sh — do not edit by hand */"
    echo "/* overrides the --color-* vars declared in styles.css */"
    jq -r '
      .special.background as $bg |
      .special.foreground as $fg |
      .colors as $c |
      ":root {",
      "  --color-foreground: \($fg);",
      "  --color-foreground-30: \($fg)4d;",
      "  --color-background: \($bg);",
      "  --color-background-90: \($bg)e6;",
      "  --color-black: \($c.color8 // $c.color0);",
      "  --color-red: \($c.color1);",
      "  --color-green: \($c.color2);",
      "  --color-yellow: \($c.color3);",
      "  --color-blue: \($c.color4);",
      "  --color-magenta: \($c.color5);",
      "  --color-cyan: \($c.color6);",
      "  --color-white: \($c.color7);",
      "}"
    ' "$CACHE"
  } > "$CSS_OUT"
  echo "CSS variables written to $CSS_OUT"
}

show() {
  [ -f "$CACHE" ] || { echo "No palette yet — run: $0 gen <image>"; exit 1; }
  echo
  jq -r '.colors | to_entries[] | "\(.key)\t\(.value)"' "$CACHE" |
    while IFS=$'\t' read -r name hex; do
      local r g b
      r=$((16#${hex:1:2})); g=$((16#${hex:3:2})); b=$((16#${hex:5:2}))
      printf '\033[48;2;%d;%d;%dm    \033[0m %-8s %s\n' "$r" "$g" "$b" "$name" "$hex"
    done
}

STYLE_LINK='<link rel="stylesheet" type="text/css" href="./styles.css" />'
WAL_LINK='<link rel="stylesheet" type="text/css" href="./wal.css" />'

bar_htmls() {
  local src rices
  src="$(cygpath -u "$(chezmoi source-path)" 2>/dev/null || chezmoi source-path)"
  rices="$src/dot_rice-manager/rices"
  [ -d "$rices" ] || { echo "Can't find $rices" >&2; exit 1; }
  find "$rices" -path "*/dotfile-bar/bar.html" | sort
}

wire() {
  local n=0
  while read -r f; do
    if grep -qF './wal.css' "$f"; then
      echo "  already wired  ${f##*/rices/}"
      continue
    fi
    grep -qF './styles.css' "$f" || { echo "  NO styles.css link  ${f##*/rices/}"; continue; }
    local tmp; tmp="$(mktemp)"
    awk -v wal="$WAL_LINK" '
      { print }
      /href="\.\/styles\.css"/ && !done {
        match($0, /^[ \t]*/)
        indent = substr($0, 1, RLENGTH)
        print ""
        print indent "<!-- Generated palette; overrides styles.css. Absent until walsync runs. -->"
        print indent wal
        done = 1
      }
    ' "$f" > "$tmp"
    mv "$tmp" "$f"
    echo "  wired          ${f##*/rices/}"
    n=$((n+1))
  done < <(bar_htmls)
  echo
  echo "Wired $n file(s). Next: chezmoi apply"
}

unwire() {
  while read -r f; do
    grep -qF './wal.css' "$f" || continue
    local tmp; tmp="$(mktemp)"
    grep -vF './wal.css' "$f" | grep -vF 'Generated palette; overrides styles.css' > "$tmp"
    mv "$tmp" "$f"
    echo "  unwired  ${f##*/rices/}"
  done < <(bar_htmls)
  echo
  echo "Next: chezmoi apply"
}

GLAZE_CFG="$HOME/.glzr/glazewm/config.yaml"
FOCUSED_KEY="color7"
UNFOCUSED_KEY="background"

palette_color() {  # palette_color <key>  — colorN, or background/foreground
  case "$1" in
    background|foreground|cursor) jq -r ".special.$1" "$CACHE" ;;
    *)                            jq -r ".colors.$1"  "$CACHE" ;;
  esac
}

glaze() {
  [ -f "$CACHE" ]     || { echo "No palette yet — run: $0 gen <image>"; exit 1; }
  [ -f "$GLAZE_CFG" ] || { echo "No config at $GLAZE_CFG"; exit 1; }

  local foc unfoc tmp
  foc="$(palette_color "$FOCUSED_KEY")"
  unfoc="$(palette_color "$UNFOCUSED_KEY")"
  tmp="$(mktemp)"

  # Two `color:` keys live under border: — first in focused_window, second in
  # other_windows. Track which block we're in rather than blind-replacing.
  awk -v foc="$foc" -v unfoc="$unfoc" '
    /^[ \t]*focused_window:/  { blk = "foc" }
    /^[ \t]*other_windows:/   { blk = "unfoc" }
    /^[ \t]*color:[ \t]*"#/ {
      match($0, /^[ \t]*/)
      indent = substr($0, 1, RLENGTH)
      if (blk == "foc")        { print indent "color: \"" foc "\"";   next }
      else if (blk == "unfoc") { print indent "color: \"" unfoc "\""; next }
    }
    { print }
  ' "$GLAZE_CFG" > "$tmp"
  mv "$tmp" "$GLAZE_CFG"

  echo "GlazeWM borders: focused $foc / other $unfoc"
  glazewm command wm-reload-config >/dev/null 2>&1 \
    && echo "Config reloaded." \
    || echo "Reload failed — press alt+shift+r."
}

WE_MONITOR_KEY="Monitor0"   # WE's key for the monitor whose wallpaper drives the palette

we_config() {
  local c
  for c in \
    "/c/Program Files (x86)/Steam/steamapps/common/wallpaper_engine/config.json" \
    "/d/SteamLibrary/steamapps/common/wallpaper_engine/config.json" \
    "/e/SteamLibrary/steamapps/common/wallpaper_engine/config.json"
  do
    [ -f "$c" ] && { printf '%s' "$c"; return 0; }
  done
  return 1
}

# Path of the wallpaper asset currently assigned to $WE_MONITOR_KEY.
we_wallpaper_file() {
  local cfg
  cfg="$(we_config)" || { echo "Can't find Wallpaper Engine config.json" >&2; return 1; }

  # Target the live `wallpaperconfig` block. Saved profiles also contain a
  # `selectedwallpapers` map, but nested under `config`, so anchor on the key.
  jq -r --arg mon "$WE_MONITOR_KEY" '
    [paths as $p | select($p[-1] == "wallpaperconfig") | $p] as $wp
    | if ($wp | length) == 0 then empty
      else getpath($wp[0]).selectedwallpapers[$mon].file // empty
      end
  ' "$cfg" 2>/dev/null | head -n1
}

# Preview image for that wallpaper (pywal can't sample a running scene).
we_current() {
  local file dir preview
  file="$(we_wallpaper_file)"
  [ -n "$file" ] || {
    echo "No wallpaper found for $WE_MONITOR_KEY" >&2
    echo "Available monitor keys:" >&2
    jq -r '[paths as $p | select($p[-1] == "wallpaperconfig") | $p] as $wp
           | getpath($wp[0]).selectedwallpapers | keys[]' "$(we_config)" >&2 2>/dev/null
    return 1
  }
  dir="$(dirname "$(cygpath -u "$file" 2>/dev/null || printf '%s' "$file")")"
  preview="$(ls "$dir"/preview.* 2>/dev/null | head -n1 || true)"
  [ -n "$preview" ] || { echo "No preview.* in $dir" >&2; return 1; }
  printf '%s\n' "$preview"
}

# Poll config.json; resync when the primary monitor's wallpaper actually changes.
watch_we() {
  local cfg interval last_mtime mtime current saved
  cfg="$(we_config)" || { echo "Can't find Wallpaper Engine config.json" >&2; exit 1; }
  interval="${1:-5}"
  last_mtime=""
  echo "Watching $cfg every ${interval}s. Ctrl+C to stop."

  while true; do
    mtime="$(stat -c %Y "$cfg" 2>/dev/null || echo 0)"
    if [ "$mtime" != "$last_mtime" ]; then
      last_mtime="$mtime"
      current="$(we_current 2>/dev/null || true)"
      saved="$([ -f "$SOURCE_FILE" ] && cat "$SOURCE_FILE" || true)"
      if [ -n "$current" ] && [ "$current" != "$saved" ]; then
        echo "Wallpaper changed -> $current"
        sync_all "$current" || echo "  sync failed; continuing to watch."
      fi
    fi
    sleep "$interval"
  done
}

restart_zebar() {
  taskkill -IM zebar.exe -F >/dev/null 2>&1 || true
  sleep 1
  start zebar >/dev/null 2>&1 &
  echo "Zebar restarted."
}

sync_all() {  # sync_all [image]
  gen "${1:-}" || return 1
  glaze
  restart_zebar
}

we_scan() {
  local roots=(
    "/c/Program Files (x86)/Steam/steamapps/workshop/content/431960"
    "/d/SteamLibrary/steamapps/workshop/content/431960"
    "/e/SteamLibrary/steamapps/workshop/content/431960"
  )
  local found=0
  for root in "${roots[@]}"; do
    [ -d "$root" ] || continue
    found=1
    echo "== $root"
    for d in "$root"/*/; do
      local id title preview
      id="$(basename "$d")"
      title="$(jq -r '.title // "?"' "$d/project.json" 2>/dev/null || echo '?')"
      preview="$(ls "$d"preview.* 2>/dev/null | head -n1 || true)"
      printf '  %-12s %-40s %s\n' "$id" "${title:0:40}" "${preview:-no preview}"
    done
  done
  [ "$found" -eq 1 ] || echo "No workshop folder found — pass your Steam library path manually."
}

cmd="${1:-}"; shift || true
case "$cmd" in
  gen)
    img=""
    if [ $# -ge 1 ] && [ "${1#-}" = "$1" ]; then img="$1"; shift; fi
    while [ $# -gt 0 ]; do
      case "$1" in
        -b|--backend) BACKEND="$2"; shift 2 ;;
        *) echo "unknown option: $1"; exit 1 ;;
      esac
    done
    gen "$img"
    ;;
  source)
    [ $# -eq 1 ] || { echo "source needs one image path"; exit 1; }
    [ -f "$1" ] || { echo "No such image: $1"; exit 1; }
    set_source "$1"
    ;;
  sync)
    img=""
    if [ $# -ge 1 ]; then img="$1"; shift; fi
    sync_all "$img"
    ;;
  show)    show ;;
  glaze)
    while [ $# -gt 0 ]; do
      case "$1" in
        --focused)   FOCUSED_KEY="$2"; shift 2 ;;
        --unfocused) UNFOCUSED_KEY="$2"; shift 2 ;;
        *) echo "unknown option: $1"; exit 1 ;;
      esac
    done
    glaze
    ;;
  wire)    wire ;;
  unwire)  unwire ;;
  we-current)
    [ $# -eq 0 ] || WE_MONITOR_KEY="$1"
    we_current
    ;;
  watch)
    watch_we "${1:-5}"
    ;;
  we-scan) we_scan ;;
  *) sed -n '3,16p' "$0"; exit 1 ;;
esac
